### ISSUE TITLE
Is it possible to dockerize this? 

### ISSUE THREAD

**Issue by Buronn** [MainSilent/Discord-Screenshare#12]

**Comment by MainSilent** [comment]
I haven't tried that, The challenging part is to properly install chrome and youtube-dl since they are dependent on some libraries.
If you were able to create a Dockerfile I would be happy to add that to the repository.

**Comment by Buronn** [comment]
I have been trying, and I managed to make it run in docker, I can pass you the repository that I'm using in the meantime to do tests, I have not yet tested if it works 100%. (I had to modify part of your code and modify version issues)
https://github.com/Buronn/screen-share-discord-bot-docker

**Comment by Buronn** [comment]
I tried to do it in Alpine, but it was too complicated for the incredible amount of dependencies (chrome & selenium fault)

**Comment by MainSilent** [comment]
I appreciate your time on this project, Let me know if there is any part of code that you need more info about.

**Comment by Buronn** [comment]
I realized that it is necessary to use a program like [VcXsrv](https://sourceforge.net/projects/vcxsrv/) in the background, now I made a few last changes, and it finally works. The only annoyance is having to attach shell and then do `npm i` and `npm start`.

**Comment by MainSilent** [comment]
This issue has been closed due to inactivity, Feel free to reopen it If you have any questions.
