### ISSUE TITLE
Version Chromedriver

### ISSUE THREAD

**Issue by thurdev** [MainSilent/Discord-Screenshare#14]
Which version are u using?

I downloaded the last stable version and i get a error, i know thats not your problem maybe with a older version should work.

**Comment by MainSilent** [comment]
The chrome version I used is `88`, If the error didn't solve, I recommend checking other issues.

**Comment by thurdev** [comment]
Yeah even with chromedriver 88 still get the same error


```
node_modules\selenium-webdriver\chromium.js:615
      executor = createExecutor(service.start(), this.VENDOR_COMMAND_PREFIX)
                                        ^

TypeError: service.start is not a function
    at Function.createSession
 
```

**Comment by MainSilent** [comment]
I haven't encountered this error before, Try upgrading the `selenium-webdriver` it's currently the beta version in package.json
