### ISSUE TITLE
Why my bot is offline?

### ISSUE THREAD

**Issue by AadiNawar** [MainSilent/Discord-Screenshare#15]

**Comment by AadiNawar** [comment]
I need help my bot is offline and the script is not running

**Comment by MainSilent** [comment]
Can you explain more about the issue you have encountered?

**Comment by AadiNawar** [comment]
I am trying to run the script in repli.it but some errors are coming
Like discordstream@1 exit status 1

**Comment by AadiNawar** [comment]
Can you suggest me a good script runner please and tell the solution

**Comment by MainSilent** [comment]
Replit doesn't have the needed resource to run the script as I have mentioned in a youtube reply.

**Comment by AadiNawar** [comment]
> Replit doesn't have the needed resource to run the script as I have mentioned in a youtube reply.

I did not see the reply

**Comment by AadiNawar** [comment]
![Uploading AB8E0CEB-F23C-4202-B582-08E9AA65C4A6.jpeg…]()

**Comment by AadiNawar** [comment]
Can you suggest me a good script runner? It would help me a lot

**Comment by MainSilent** [comment]
I recommend using `vultr` or `linode` since they are metered and cost 5$ for a vps with 2GB of RAM and 1 Core CPU.

**Comment by AadiNawar** [comment]
But they are paid

**Comment by AadiNawar** [comment]
Can you help me with the coding please my discord:- Blue_i7#1087

**Comment by MainSilent** [comment]
The script is ready to use, You only need to install the dependencies and run by `npm start`

**Comment by AadiNawar** [comment]
But both are paid I am a 15 yr old boy how I am gonna pay it up

**Comment by MainSilent** [comment]
Sorry, I can only help you with the script.

**Comment by AadiNawar** [comment]
Ok thanks can you give me your bot

**Comment by AadiNawar** [comment]
I wanna see it running

**Comment by MainSilent** [comment]
This is a selfbot, I currently don't have it running
