### ISSUE TITLE
Yo 

### ISSUE THREAD

**Issue by deep2828** [MainSilent/Discord-Screenshare#16]
Hey, I'm mobile user can we run on replit (https://replit.com/~) 
And I run showing this error  ( https://media.discordapp.net/attachments/911984497703125013/936962535217823824/Screenshot_20220129-180427_Chrome.jpg ) please fix

**Comment by MainSilent** [comment]
Replit doesn't have enough resource to run the script, The shown error is duplicate #3

**Comment by deep2828** [comment]
> Replit doesn't have enough resource to run the script, The shown error is duplicate #3

Bro I upgrade my replit to node v14 now showing 'id' Error please make for replit

**Comment by MainSilent** [comment]
Please check all the issues before opening a new one
The issues that you have encountered are very common and have been asked before
For example the `id` issue is duplicate and pined #2
