### ISSUE TITLE
Play local videos

### ISSUE THREAD

**Issue by phere-x** [MainSilent/Discord-Screenshare#18]
Would just passing it the local path to the video work? If not possible, can this be a feature looked into to add.

**Comment by MainSilent** [comment]
Have you tried it? This is actually very simple you just need to change line 22 in `stream.js`

**Comment by MainSilent** [comment]
This issue has been closed due to inactivity

**Comment by phere-x** [comment]
I'm not clear on what to change line 22 to. What should I put there?

**Comment by MainSilent** [comment]
There is a `url` variable that loads the url into html video element, If you have a local file change it to (for example) `file:///home/test/Downloads/myVideo.mp4`
