### ISSUE TITLE
Cannot send an empty message

### ISSUE THREAD

**Issue by phere-x** [MainSilent/Discord-Screenshare#20]
Starts using `npm start` 
`Webdriver started
Bot started`

Then when I type `*help`

```
discodscreenshare/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85
              new DiscordAPIError(res.request.path, res.body, res.request.method) : err);
              ^

DiscordAPIError: Cannot send an empty message
    at /dato/mov/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /dato/mov/node_modules/snekfetch/src/index.js:215:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  path: '/api/v7/channels/751611339297783886/messages',
  code: 50006,
  method: 'POST'
}
```

**Comment by MainSilent** [comment]
I also encountered this error, There might be some changes for embed API which I'm checking.
But it worked for normal message, Does it also work for you when using `*p` command? `*p url`

**Comment by phere-x** [comment]
Using both gives `You need to be in a voice channel to use this command`

I am in a VC & this account has admin permissions.

**Comment by MainSilent** [comment]
This is a know bug in discord.js 11, When you started the bot you need to leave and join the voice channel so the bot have the voice status of the user

**Comment by MainSilent** [comment]
Checkout last commit for `help` message fix, It appears Discord has stopped sending embed messages from user accounts

**Comment by phere-x** [comment]
Ok. it's sending messages fine now. I probably should've mentioned that to help a little, as I heard bout it a few days ago

**Comment by MainSilent** [comment]
Were you able to set it up?

**Comment by phere-x** [comment]
Yes, download seems a bit slow but not sure where's the issue. Streaming the video is quite choppy too. My local machines internet speeds are perfectly fine. Processing doesnt start bottlenecking.

- I'm running it in a Ubtuntu 20.04 VM, running on Proxmox

**Comment by MainSilent** [comment]
For the download use `yt-dlp` instead of `youtueb-dl` for some people worked better, We were able to get fast and high quality stream with 4GB of ram and 2 core cpu using `vultr` VPS, They are metered and cheap you can try that to see if it makes any difference

**Comment by MainSilent** [comment]
BTW make sure the video is 720P and less that 30 FPS, Some youtube videos were 60 fps and it was extremely choppy.
