### ISSUE TITLE
Slow response time for bot joining VC & starting stream

### ISSUE THREAD

**Issue by phere-x** [MainSilent/Discord-Screenshare#21]
I had downloaded a YT 720p,30fps video, verified it was downloaded & ready.  But the bot did not join till about 5 mins after using the command `*play`. and another 5+ more mins went by before it started streaming. And even then it was stuck on the begininng frame. 

Is there a way I can troubleshoot it to figure out the issue?

**Comment by MainSilent** [comment]
The bot has been made headless to use on servers without GUI, In `stream.js` comment line 167, It will show you the browser and there will be more details on how it's working.

**Comment by MainSilent** [comment]
Does this just happen with YouTube videos? or it's the same when using local videos?

**Comment by phere-x** [comment]
> Does this just happen with YouTube videos? or it's the same when using local videos?

I have only tried it with YouTube videos so far. No local video testing done by me yet.
