### ISSUE TITLE
Error: spawn youtube-dl ENOENT

### ISSUE THREAD

**Issue by itsbeni** [MainSilent/Discord-Screenshare#24]
Error code: -2

Process error:
Error: spawn youtube-dl ENOENT
im having this.. i run that on debian linux and i did everything.. how i can fix ろ𝐁𝐞𝐧𝐢 𝐂𝐢𝐞𝐥𝐨#6666 dm for help or here

**Comment by MainSilent** [comment]
Your issue is duplicate, I have mentioned a fix on the other same issue that you have opened, Please delete this issue.
