### ISSUE TITLE
Stream does not display image

### ISSUE THREAD

**Issue by TerminalPR0** [MainSilent/Discord-Screenshare#27]
I tried to update the library youtube-dl-wrap, but it did not help.
https://imgur.com/a/wUMFxsE
How can I fix this error?

**Comment by MainSilent** [comment]
Can you send more details about the environment?

**Comment by TerminalPR0** [comment]
Linux Ubuntu 20.04 LTS ARM64
Node.JS v17.6.0

**Comment by MainSilent** [comment]
Not exactly sure what is causing the error since I'm not able to reproduce it, I recommend testing with this environment:

> Ubuntu 20.04 x86 / AMD64
> chrome & chromedriver 88
> nodejs 14

If that didn't work test the dependencies separately, You also mentioned `youtube-dl-wrap` if that is the issue you need to ask it in their repository page.

**Comment by TerminalPR0** [comment]
I have chromium 98 installed.
i can not install chrome.

**Comment by TerminalPR0** [comment]
Can i get ur discord?

**Comment by MainSilent** [comment]
I cannot guarantee the working of the project on the environment you have, You may consider using a VPS or emulator for ubuntu x86 / AMD64

**Comment by TerminalPR0** [comment]
> Can i get ur discord?

**Comment by MainSilent** [comment]
No

**Comment by TerminalPR0** [comment]
I started the project on the environment where you advised me to do it, but the bot also does not want to download the video.
https://imgur.com/a/MVQ54SA
https://imgur.com/a/iLK5XtO

**Comment by MainSilent** [comment]
I'm not sure about `Katacoda` but to troubleshoot first try with a direct link for example [bunny](https://test-videos.co.uk/bigbuckbunny/mp4-h264) videos, If that didn't work double check the nodejs and chrome version

**Comment by TerminalPR0** [comment]
https://imgur.com/a/AMh4jk8
https://imgur.com/a/RwND4Q6

**Comment by TerminalPR0** [comment]
> I'm not sure about `Katacoda` but to troubleshoot first try with a direct link for example [bunny](https://test-videos.co.uk/bigbuckbunny/mp4-h264) videos, If that didn't work double check the nodejs and chrome version

Same. The picture is not visible.

**Comment by TerminalPR0** [comment]
nodejs and chrome is latest stable version

**Comment by MainSilent** [comment]
> Same. The picture is not visible.

Is not visible? does it join the voice channel and start screen share?
