### ISSUE TITLE
Info on possible code upgrades

### ISSUE THREAD

**Issue by Francesco99d** [MainSilent/Discord-Screenshare#30]
Hi, I was able to get the code to work and run the bot (I had to set the node.js version to 14). The problem is that whatever YouTube link I type in, I will always get this error:
`🚫 MEDIA_ELEMENT_ERROR: Format error`
On that note, I was wondering if you were going to update the code to the new version of the discord API and maybe fix any issues that are present. Thanks and good work

**Comment by MainSilent** [comment]
I haven't tested it in a while, Is there any issues that are related to discord API update? The last one was embed messages that apparently stopped working for user accounts, We are using discordjs@11 If we upgrade that we won't be able to do selfbot.

What version of chrome are you using? Does it work fine with a direct video url?

**Comment by Francesco99d** [comment]
I've done some testing and I keep getting the error: `🚫 MEDIA_ELEMENT_ERROR: Format error`
when I insert a youtube link, while trying with a direct .mp4 link it would seem to give me confirmation of successful download, but actually I get [errors in console](https://pastebin.com/MwemL2k6):

Here are some screenshots:
![Immagine 2022-03-24 163429](https://user-images.githubusercontent.com/84293168/159953138-b053843d-983f-43bf-a072-8a1b48ff32b5.png)
![Immagine 2022-03-24 163445](https://user-images.githubusercontent.com/84293168/159954586-a2dcf6f7-1f8d-4165-a72c-080e91202c5e.png)

P.s. The account doesn't connect to the voice channel and if I do *play nothing happens. I confirm that the embed messages don't work. I'm using chromedriver version 99.0.4844.82 (the latest stable version). If it can be useful I'm trying it on Windows, not having at the moment a pc with linux.

**Comment by MainSilent** [comment]
It currently doesn't work on windows, You can install a virtual machine like `vmbox` and install ubuntu, I also recommend using chrome version 88

**Comment by Francesco99d** [comment]
In the coming days I'll try to use linux and see if I can make it work. Only one thing, in order to work, the bot needs some dependencies among these the chromedriver and consequently google installed on the machine, so I was wondering if there was a simple way to install all the dependencies of the case (perhaps through a script attached to the bot) so that it can be more practical and simple to use the bot on a host site (assuming that everything still works). Could you help me out on this? Thanks a lot and good work

**Comment by MainSilent** [comment]
Honestly, it should work on windows, There are some hardcoded UNIX commands..., If that is the only reason this doesn't work on windows I'll do a commit now since so many people are using windows.

**Comment by MainSilent** [comment]
No, there are more even when using the same dependencies version, The requirements that worked for most people are:
      
```
ubuntu or other distros (not WSL)
chrome & chromedriver 88
nodejs v14
```
I should also mention since we are using headless chrome and discord we need to have at least 2GB of ram and 1 core CPU, This is the reason that it doesn't work on replit.

**Comment by Francesco99d** [comment]
Hi, I installed ubuntu in virtual machine along with everything needed to get the bot working, but apparently I missed something.... Since I am now getting a [new error](https://pastebin.com/nTMM6Ybw): https://pastebin.com/nTMM6Ybw
At this point I thank you for the availability, but I think I'm not able to make it work, so I'll drop the project. Good work again

P.s. I'm not good with linux, surely the problem is my fault since on windows it more or less worked if it wasn't for the errors in the processing phase.

**Comment by MainSilent** [comment]
It is not challenging to make it work, There are many closed issues with the error you have encountered.
