### ISSUE TITLE
Video download slow

### ISSUE THREAD

**Issue by Kaanekiiii** [MainSilent/Discord-Screenshare#31]
as described in the YouTube comments. The YouTube download is slow :/ A video that is 1 minute long takes 2 minutes to download. I did it with a direct link, it was quick and without Problems there

**Comment by MainSilent** [comment]
Are you sure the bot is using yt-dlp?

**Comment by Kaanekiiii** [comment]
I am not sure but I have installed yt-dlp

**Comment by MainSilent** [comment]
First, make sure youtube-dl is not installed and then find yt-dlp location by this command `whereis yt-dlp` And rename the file to `youtube-dl`, Also make sure when using youtube-dl command it run yt-dlp.

**Comment by Kaanekiiii** [comment]
Oh now! Thank you! Download is really fast now :D

**Comment by MainSilent** [comment]
I'm glad you were able to set up the bot since for so many people is challenging...
