### ISSUE TITLE
Bot Can't join to voice

### ISSUE THREAD

**Issue by MrSamix** [MainSilent/Discord-Screenshare#32]
Webdriver started
Bot started
Loading... (no join to voice)
Play (no join to voice)

**Comment by MainSilent** [comment]
Is there more output on terminal? What environment are you using (os, distro, nodejs, chrome)?

**Comment by MrSamix** [comment]
> Is there more output on terminal? What environment are you using (os, distro, nodejs, chrome)?

No
(Os: Ubuntu 20.04, nodejs 14, chrome and chromedriver 88)

**Comment by MainSilent** [comment]
Is it WSL? Is it a user or bot token?

**Comment by MrSamix** [comment]
> Is it WSL? Is it a user or bot token?

No, it's a virtual machine.
Bot token

**Comment by MainSilent** [comment]
It's a self bot, Duplicate #26
