### ISSUE TITLE
Error: You should be in a voice channel

### ISSUE THREAD

**Issue by UNITY002** [MainSilent/Discord-Screenshare#33]
I tried everything, everything I could. Changed the node modules, and modified the file, Used discord.js-self bot library still the same.  After everything 
bot started but 
![image](https://user-images.githubusercontent.com/76200506/162156213-1f028383-f299-4f15-8ec3-e019c864d3cb.png)
 
Please fix this!

**Comment by MainSilent** [comment]
This is a caching issue, When bot started you need to leave and join the voice channel so it cache that in memory.

**Comment by MainSilent** [comment]
Is it accessible via PATH env?

**Comment by UNITY002** [comment]
> Is it accessible via PATH env?

No

**Comment by MainSilent** [comment]
It should be

**Comment by UNITY002** [comment]
What exactly do you mean? Could you please explain more?

**Comment by MainSilent** [comment]
The `chromedriver` binary should be in `/bin` directory, You should be able to run the binary in any directory.

**Comment by UNITY002** [comment]
> The `chromedriver` binary should be in `/bin` directory, You should be able to run the binary in any directory.

I'm doing a clean install again on ubuntu let's see.  I will reply soon

**Comment by UNITY002** [comment]
> The `chromedriver` binary should be in `/bin` directory, You should be able to run the binary in any directory.

![image](https://user-images.githubusercontent.com/76200506/162179831-7d825925-25e8-4ad8-99f5-4ac6bc450bfc.png)
![image](https://user-images.githubusercontent.com/76200506/162180248-299eb07d-f690-47f3-8692-8718e60adbf6.png)

**Comment by UNITY002** [comment]
As you can see webdriver started but not working

**Comment by MainSilent** [comment]
Duplicate #3
