### ISSUE TITLE
Cannot read of undefined (reading 'id')

### ISSUE THREAD

**Issue by K14it5mCFQZLF7BUVKF5QycA04yUjeak** [MainSilent/Discord-Screenshare#37]
![Screenshot 2022-05-06 074714](https://user-images.githubusercontent.com/104942135/167063835-b3e806b0-3aff-46c8-bc18-7640d9c26f6c.png)
just installed the bot and followed the steps but it seems like it crash while trying to login

**Comment by MainSilent** [comment]
Duplicate #2

**Comment by K14it5mCFQZLF7BUVKF5QycA04yUjeak** [comment]
> Duplicate #2

i didn't understand anything from that ticket there's no solution , all i know is just update discord.js to v12 ?
tell me what's to do because the issue that exist is not clear enough

**Comment by MainSilent** [comment]
File: node_modules\discord.js\src\client\ClientDataManager.js

line: 81

Add `if(channel != null)`
