### ISSUE TITLE
Not streaming on ubuntu 20.04

### ISSUE THREAD

**Issue by UTrosh** [MainSilent/Discord-Screenshare#40]
So, the command work etc. it start but, 
![image](https://user-images.githubusercontent.com/73399986/168444143-b70ab6a7-8e44-4889-8551-1205259f9bc1.png)
maybe need a gpu?

**Comment by MainSilent** [comment]
Can you explain more about the issue? Including nodejs and chrome version

**Comment by UTrosh** [comment]
So, thé vidéo is working but the song is in retard

**Comment by UTrosh** [comment]
Server's spec :
Xeon E5 2570 v2
32gb of ram

No GPU/APU is it due to that ?

**Comment by UTrosh** [comment]
And for version, chrome 101
Nodejs 14

**Comment by MainSilent** [comment]
It doesn't need GUI but you can disable headless in stream.js line 167, Can you try with chrome 88?

**Comment by MainSilent** [comment]
Is the audio not synced with a youtube video or a direct video link?

**Comment by UTrosh** [comment]
so, i will try with chrome 88, but then the audio is with the youtube video, but its a little bit retard, like 1-2s

**Comment by UTrosh** [comment]
no change with chrome 88

**Comment by MainSilent** [comment]
> so, i will try with chrome 88, but then the audio is with the youtube video, but its a little bit retard, like 1-2s

Is it the same with a direct video link? Based on your hardware it appears to be capable without causing audio delay, I'm not sure how to fix it.

**Comment by UTrosh** [comment]
> > so, i will try with chrome 88, but then the audio is with the youtube video, but its a little bit retard, like 1-2s
> 
> Is it the same with a direct video link? Based on your hardware it appears to be capable without causing audio delay, I'm not sure how to fix it.

yes, but maybe need a better gpu / cpu?

**Comment by MainSilent** [comment]
I'm not sure but I test it on vultr VPS and didn't get any audio lag (using chrome 88), They have metered services less than a dollar to test for a day.
