### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by AhmedMondo** [MainSilent/Discord-Screenshare#41]
I have an Idea for a new code 

Its Bot Adder 
Example: 

I gave the program bot invite link 
It will add it to specify guild which i choose it by id and it will automatically add it into that guild and bypassing the captcha.

Thx.

I didnt find any other ways to contact you :)

**Comment by MainSilent** [comment]
I used to try these projects but they are not easy as it sounds and discord has many limitations that make it time consuming, I have left discord and stopped working on new related projects.
