### ISSUE TITLE
Change module

### ISSUE THREAD

**Issue by aiko-chan-ai** [MainSilent/Discord-Screenshare#43]
i think you should use newer discord.js module which supports selfbot (v11 has broken stage channel) and use yt-dlp instead of youtube-dl to speed up video loading

Modules I use:
+ yt-dlp-wrap
+ discord.js-selfbot-v13

![image](https://user-images.githubusercontent.com/71698422/169533237-c989aedc-e8ad-4934-b999-05d3d90fcd18.png)

**Comment by MainSilent** [comment]
I'm planning based on the #38 issue to try other methods for streaming youtube videos so it wouldn't need to wait for the video to finish downloading, I'll check `discord.js-selfbot-v13`, I was mostly concerned about malware so decided to use `discord.js`.
Please keep this issue open for now.

**Comment by MainSilent** [comment]
I now realized you are the owner of that library

**Comment by aiko-chan-ai** [comment]
> I'm planning based on the #38 issue to try other methods for streaming youtube videos so it wouldn't need to wait for the video to finish downloading, I'll check `discord.js-selfbot-v13`, I was mostly concerned about malware so decided to use `discord.js`. Please keep this issue open for now.

I am waiting for that

**Comment by pengengantibaju** [comment]
i still got chromedriver eror nodejs 16

**Comment by MainSilent** [comment]
Thanks for the library. a8093ea
