### ISSUE TITLE
WebContentsDelegate::CheckMediaAccessPermission: Not supported.

### ISSUE THREAD

**Issue by UNITY002** [MainSilent/Discord-Screenshare#46]
![image](https://user-images.githubusercontent.com/76200506/170320518-c0e66899-b19d-4b24-b2c7-2438296a12ce.png)

**Comment by MainSilent** [comment]
What is the chrome version?

**Comment by UNITY002** [comment]
> 
Chromedriver 100
https://chromedriver.storage.googleapis.com/index.html?path=100.0.4896.60/

**Comment by MainSilent** [comment]
I recommend the below environment
Ubuntu
Nodejs 14
Chrome 88

**Comment by UNITY002** [comment]
I'll check
