### ISSUE TITLE
WebDriverError: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by rich1488** [MainSilent/Discord-Screenshare#50]
Well I was able to get it running on my raspberry pi 4, but it was terrible- sluggish and bad quality. I'm sure there's some way to improve it but I don't have the knowledge for that.

So I'm using an AWS EC2 instance to see if I can get this running, ran into a lot off issues which I've managed to fix until this one- not some easy workaround or fix (or at least none I found on google/stackoverflow)

Anyone run into this issue?

`   let err = new ctor(data.message)
              ^

WebDriverError: unknown error: DevToolsActivePort file doesn't exist
    at Object.throwDecodedError (/home/ubuntu/videostream/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/home/ubuntu/videostream/node_modules/selenium-webdriver/lib/http.js:549:13)
    at Executor.execute (/home/ubuntu/videostream/node_modules/selenium-webdriver/lib/http.js:475:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {`

**Comment by MainSilent** [comment]
It appears to be a dependency issue, I recommend using the Dockerfile.

**Comment by rich1488** [comment]
> It appears to be a dependency issue, I recommend using the Dockerfile.

So i'm trying out this Docker thing, but run into this when I build
`COPY failed: file not found in build context or excluded by .dockerignore: stat .env: file does not exist`

**Comment by MainSilent** [comment]
Make sure to have the `.env` file in the same directory as Dockerfile.

**Comment by rich1488** [comment]
> Make sure to have the `.env` file in the same directory as Dockerfile.

Oh ok. I thought docker clones the repo already, so I just need .env in before running build and it will clone repo as well?

**Comment by MainSilent** [comment]
It will run after the build, The `.env` is copied for configuration.

**Comment by rich1488** [comment]
> It will run after the build, The `.env` is copied for configuration.

I can't get it to run no matter what I do...

I do the build and it ends with this error `error Couldn't find a package.json file in "/videostream"`

then i try to run it `docker run dockerfile`  or `sudo docker run dockerfile` i get these;

```ubuntu@ip-172-31-23-133:~/videostream$ docker run dockerfile
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
ubuntu@ip-172-31-23-133:~/videostream$ sudo docker run dockerfile
Unable to find image 'dockerfile:latest' locally
docker: Error response from daemon: pull access denied for dockerfile, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.```

**Comment by MainSilent** [comment]
This is docker related issue, It's not able to make a connection with docker.

**Comment by rich1488** [comment]
> This is docker related issue, It's not able to make a connection with docker.

Ok iI got it running but got that error for stage channels. Where is the node_modules folder stored at so I can go in and edit it? After docker build, where it does save all the files?

**Comment by MainSilent** [comment]
The new version is using `discord.js-selfbot-v13`, Stage channels shouldn't be an issue.

**Comment by rich1488** [comment]
> The new version is using `discord.js-selfbot-v13`, Stage channels shouldn't be an issue.

Ok so I just did a brand new clone, edited the .env, build from dockerfile in it. but getting this error
```/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129:26)
    at Client.login (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/Client.js:335:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}```

**Comment by rich1488** [comment]
where does docker store all the libraries/packages?

**Comment by ExclusiveRishi** [comment]
> > The new version is using `discord.js-selfbot-v13`, Stage channels shouldn't be an issue.
> 
> Ok so I just did a brand new clone, edited the .env, build from dockerfile in it. but got this error after build.
> 
> ```
>     const invalidToken = new Error(WSCodes[4004]);
>                          ^
> 
> Error [TOKEN_INVALID]: An invalid token was provided.
>     at WebSocketManager.connect (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129:26)
>     at Client.login (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/Client.js:335:21)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   [Symbol(code)]: 'TOKEN_INVALID'
> }```
> ```

Hey @rich1488 I'm facing same issue,
Can you tell me how did you fixed it?

**Comment by MainSilent** [comment]
> > > The new version is using `discord.js-selfbot-v13`, Stage channels shouldn't be an issue.
> > 
> > 
> > Ok so I just did a brand new clone, edited the .env, build from dockerfile in it. but got this error after build.
> > ```
> >     const invalidToken = new Error(WSCodes[4004]);
> >                          ^
> > 
> > Error [TOKEN_INVALID]: An invalid token was provided.
> >     at WebSocketManager.connect (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:129:26)
> >     at Client.login (/Discord-Screenshare/node_modules/discord.js-selfbot-v13/src/client/Client.js:335:21)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
> >   [Symbol(code)]: 'TOKEN_INVALID'
> > }```
> > ```
> 
> Hey @rich1488 I'm facing same issue, Can you tell me how did you fixed it?

Have you set the token in .env?

**Comment by ExclusiveRishi** [comment]
Yup I have, tried both with and without quotes
