### ISSUE TITLE
bot cant show screen only stuck on loading

### ISSUE THREAD

**Issue by pengengantibaju** [MainSilent/Discord-Screenshare#51]
![image](https://user-images.githubusercontent.com/92777707/172864850-15325752-359a-48da-ae74-90425e731195.png)

**Comment by MainSilent** [comment]
Are you using the Dockerfile? Most of these issues are related to dependencies.

**Comment by pengengantibaju** [comment]
yes sir i use docker.. i do all on read.md

**Comment by MainSilent** [comment]
Was that a live video as it said on the title? Currently, it doesn't support HLS videos.

**Comment by pengengantibaju** [comment]
yes sir only audio.. is any way to reach you on discord ? i need help

**Comment by MainSilent** [comment]
I'm not available but I believe troubleshooting and checking other issues might help.
