### ISSUE TITLE
ChromeDriver could not be found 

### ISSUE THREAD

**Issue by 77PC** [MainSilent/Discord-Screenshare#52]
my device :

Samsung J6 
Android 10 
Non Rooted 

information that might help :
Termux 0.118.0 
Chrome 102.0.5005.125

this is the error i get :

> /data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/chrome.js:161
>       throw Error(
>       ^
> 
> Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
>     at new ServiceBuilder (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/chrome.js:161:13)
>     at thenableWebDriverProxy.getDefaultService (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/chrome.js:278:22)
>     at thenableWebDriverProxy.createSession (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/chromium.js:668:49)
>     at thenableWebDriverProxy.createSession (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/chrome.js:240:13)
>     at createDriver (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/index.js:146:33)
>     at Builder.build (/data/data/com.termux/files/home/vc/node_modules/selenium-webdriver/index.js:674:16)
>     at new Stream (/data/data/com.termux/files/home/vc/stream.js:153:101)
>     at Object.<anonymous> (/data/data/com.termux/files/home/vc/main.js:14:14)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
> 
> Node.js v18.3.0
> ~/vc $

**Comment by MainSilent** [comment]
Currently, I'm not able to guarantee the working of this project on ARM devices.
