### ISSUE TITLE
Run issuss

### ISSUE THREAD

**Issue by Zsl8** [MainSilent/Discord-Screenshare#55]
When i run the bot using the *p command it starts but the screen just loading forever without showing any thing

![image](https://user-images.githubusercontent.com/71377428/175554034-112e7f7a-c4dd-45cf-9fee-11e5b6c61ef3.png)

**Comment by MainSilent** [comment]
What is the exact command? Is there any error on terminal?

**Comment by Zsl8** [comment]
The command is
*p https://www.youtube.com/watch?v=YE7VzlLtp-4
Then the bot joins the rome and just loading
No errors i consoled the out put url from the youtube package and it's working normaly

**Comment by Zsl8** [comment]
Yes

**Comment by MainSilent** [comment]
Do you send `*play` command after the video is loaded? As it'll be mentioned.

**Comment by MainSilent** [comment]
I didn't encounter the issue.

**Comment by Zsl8** [comment]
naturally i sent the `*play` command after the stream is started

**Comment by MainSilent** [comment]
> naturally i sent the `*play` command after the stream is started

Would it play after `*play`? With the current description, I'm not able to reproduce the issue.
