### ISSUE TITLE
Yarn Issue

### ISSUE THREAD

**Issue by LeGamerDu92** [MainSilent/Discord-Screenshare#60]
When I run the Dockerfile, it says me :

> 
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> The command '/bin/sh -c yarn install' returned a non-zero code: 1

and when i run the command `/bin/sh -c yarn install` :
>
>00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

Still on the raspberry Pi but not the same error

**Comment by MainSilent** [comment]
Can you try replacing line 14 of Dockerfile with `RUN npm i`

**Comment by MainSilent** [comment]
Have you read the log?

**Comment by LeGamerDu92** [comment]
it's a new file ? 
![image](https://user-images.githubusercontent.com/84980479/176659817-1ab5a9cb-522b-4618-a5c2-38892c9c9ebb.png)

**Comment by LeGamerDu92** [comment]
The full error is :

> Step 10/17 : RUN npm i
>  ---> Running in e2eb362c7f04
> npm WARN deprecated discord.js-selfbot-v13@2.2.0: Modal and Interaction fix
> npm ERR! code 1
> npm ERR! path /Discord-Screenshare/node_modules/bufferutil
> npm ERR! command failed
> npm ERR! command sh -c node-gyp-build
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@17.9.0 | linux | arm64
> npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
> npm ERR! gyp http GET https://nodejs.org/download/release/v17.9.0/node-v17.9.0-headers.tar.gz
> npm ERR! gyp http 200 https://nodejs.org/download/release/v17.9.0/node-v17.9.0-headers.tar.gz
> npm ERR! gyp http GET https://nodejs.org/download/release/v17.9.0/SHASUMS256.txt
> npm ERR! gyp http 200 https://nodejs.org/download/release/v17.9.0/SHASUMS256.txt
> npm ERR! gyp info spawn /usr/bin/python3
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'make',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/Discord-Screenshare/node_modules/bufferutil/build/config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/root/.cache/node-gyp/17.9.0/include/node/common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/17.9.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/17.9.0/<(target_arch)/node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Discord-Screenshare/node_modules/bufferutil',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp ERR! build error
> npm ERR! gyp ERR! stack Error: not found: make
> npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
> npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
> npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
> npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
> npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
> npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
> npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
> npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
> npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> npm ERR! gyp ERR! System Linux 5.15.32-v8+
> npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd /Discord-Screenshare/node_modules/bufferutil
> npm ERR! gyp ERR! node -v v17.9.0
> npm ERR! gyp ERR! node-gyp -v v9.0.0
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-06-30T10_54_42_426Z-debug-0.log
> The command '/bin/sh -c npm i' returned a non-zero code: 1

**Comment by LeGamerDu92** [comment]
After installing gyp, the gyp command still don't work

**Comment by MainSilent** [comment]
I have no solution.

**Comment by LeGamerDu92** [comment]
Oh
