### ISSUE TITLE
spawn youtube-dl ENOENT error

### ISSUE THREAD

**Issue by MejiaAren** [MainSilent/Discord-Screenshare#8]
Error code: -4058

Process error:
Error: spawn youtube-dl ENOENT

**Comment by MainSilent** [comment]
Do you have youtube-dl installed? Is it accessible via PATH (Environment Variable)?

I suggest to install it via `pip install youtube_dl`

**Comment by itsbeni** [comment]
i did pip too but still

**Comment by itsbeni** [comment]
i guess this source have a problem for most of us at least..  if u know way to help will be glad to say it clear and btw pip is same is npm while installing youtube-dl

**Comment by MainSilent** [comment]
As long as `youtube-dl` is not accessible via `PATH`, It won't be able to download youtube videos But you are able to try a direct video link, I can't help you more.

**Comment by MainSilent** [comment]
The new update doesn't use `youtube-dl`

**Comment by rich1488** [comment]
> The new update doesn't use `youtube-dl`

What has changed? Besides the docker file you mentioned, I've barely attempted to use Docker before and would rather not

**Comment by MainSilent** [comment]
Instead of downloading a youtube video and then playing it, It will get a direct link to the video and load it.

**Comment by rich1488** [comment]
> Instead of downloading a youtube video and then playing it, It will get a direct link to the video and load it.

So it's like streaming it as it actually plays, like real-time screen recording? so this means it can play live streams that aren't videos, like news streaming right? (ik you mentioned it could before but wasnt sure, havent tested yet)

and youtube-dl isn't needed at all? i still need to fix this webdriver issue then

**Comment by MainSilent** [comment]
No `youtube-dl` is not needed, If you check the docker file there are the commands for installing needed dependencies that I believe can solve the driver issue.

I tested it with a live youtube video and it crashed, I'll let you know if I did an update for playing live videos.

**Comment by rich1488** [comment]
> No `youtube-dl` is not needed, If you check the docker file there are the commands for installing needed dependencies that I believe can solve the driver issue.
> 
> I tested it with a live youtube video and it crashed, I'll let you know if I did an update for playing live videos.

the docker file is for only running it with docker.com right? does it need to be docker, can't go without it?

**Comment by MainSilent** [comment]
It's not required but for faster setup is a better solution, For more info about docker I believe there are many articles.
